name: build
on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: build
        working-directory: scrape
        run: |
          yarn install
          yarn build
          yarn start
      - name: commit
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        run: |
          if [ `git status -s | wc -l` -ne "0" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "[ci skip] scraping done" -a
          fi
      - name: push
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
